variables:
  REPO_NAME: gitlab.com/grill-tamasi.hu/wscgo
  GO111MODULE: "on"
  VERSION: 0.1-alpha2

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.


stages:
  - test
  - build
  - deploy

test:rpizw:
  stage: test
  variables:
    GO111MODULE: "on"
  before_script:
    - echo $REPO_NAME
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
  script:
    - cd wscgo
    - go test
  tags:
    - grill-tamasi
    - rpizw
    - golang  

compile:rpizw:
  stage: build
  variables:
    GO111MODULE: "on"
  before_script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
  script:
    - go build -o $CI_PROJECT_DIR/wscgo-rpizw
  artifacts:
    paths:
      - wscgo-rpizw
  tags:
    - grill-tamasi
    - rpizw
    - golang

compile:opiz:
  stage: build
  variables:
    GO111MODULE: "on"
  before_script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
  script:
    - go get github.com/eclipse/paho.mqtt.golang
    - go get github.com/jacobsa/go-serial/serial
    - go get gopkg.in/ini.v1
    - go build -o $CI_PROJECT_DIR/wscgo-opiz
  artifacts:
    paths:
      - wscgo-opiz
  tags:
    - grill-tamasi
    - opiz
    - golang
    
## Deploy

deb:
  stage: deploy
  dependencies:
    - compile:opiz
    - compile:rpizw
  script:
    - cp wscgo-opiz wscgo
    - equivs-build wscgo-opiz.cfg
    - curl -X PUT -T wscgo-opiz_${VERSION}_armhf.deb -u$BINTRAY_USER:$BINTRAY_APIKEY "https://api.bintray.com/content/balazsgrill/home/wscgo-opiz/${VERSION}/pool/main/w/wscgo-opiz/wscgo-opiz_${VERSION}_armhf.deb;deb_distribution=unstable;deb_component=main;deb_architecture=armhf;publish=1"
    - rm wscgo
    - cp wscgo-rpizw wscgo
    - equivs-build wscgo-rpizw.cfg
    - curl -X PUT -T wscgo-rpizw_${VERSION}_armhf.deb -u$BINTRAY_USER:$BINTRAY_APIKEY "https://api.bintray.com/content/balazsgrill/home/wscgo-rpizw/${VERSION}/pool/main/w/wscgo-rpizw/wscgo-rpizw_${VERSION}_armhf.deb;deb_distribution=unstable;deb_component=main;deb_architecture=armhf;publish=1"
  artifacts:
    paths:
      - "*.deb"
  only:
    - master
  tags:
    - grill-tamasi
    - equivs
