variables:
  REPO_NAME: gitlab.com/grill-tamasi.hu/wscgo
  GO111MODULE: "on"
  VERSION: 0.5.0-beta2

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.


stages:
  - test
  - build
  - package
  - integration-test
  - deploy

test:rpizw:
  stage: test
  variables:
    GO111MODULE: "on"
    GOARM: 5
  before_script:
    - echo $REPO_NAME
    - mkdir -p $GOPATH/src/
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$(dirname $REPO_NAME)
    - cd $GOPATH/src/$REPO_NAME
  script:
    - go test -v ./devices
    - go test -v ./protocol
    - go test -v ./config
  tags:
    - grill-tamasi
    - rpizw
    - golang  

build:main:
  stage: build
  variables:
    GO111MODULE: "on"
    GOARM: 5
  script:
    - go build -o $CI_PROJECT_DIR/wscgo -ldflags "-X main.Version=${VERSION}" ./cmd/wscgo
  artifacts:
    paths:
      - wscgo
  tags:
    - grill-tamasi
    - rpizw
    - golang

build:rpizw:
  stage: build
  variables:
    GO111MODULE: "on"
    GOARM: 5
  before_script:
    - mkdir -p $GOPATH/src/
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$(dirname $REPO_NAME)
    - cd $GOPATH/src/$REPO_NAME/plugins/wiringpi
    - curl -L https://dl.bintray.com/balazsgrill/home-build/libwiringPiPca9685.a-opiz --output libwiringPiPca9685.a
    - curl -L https://dl.bintray.com/balazsgrill/home-build/pca9685.h --output pca9685.h
  script:
    - go build -o $CI_PROJECT_DIR/wscgo-wpi-rpizw.so -buildmode=plugin
  artifacts:
    paths:
      - wscgo-wpi-rpizw.so
  tags:
    - grill-tamasi
    - rpizw
    - golang

build:opiz:
  stage: build
  variables:
    GO111MODULE: "on"
    GOARM: 5
  before_script:
    - mkdir -p $GOPATH/src/
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$(dirname $REPO_NAME)
    - cd $GOPATH/src/$REPO_NAME/plugins/wiringpi
    - curl -L https://dl.bintray.com/balazsgrill/home-build/libwiringPiPca9685.a-opiz --output libwiringPiPca9685.a
    - curl -L https://dl.bintray.com/balazsgrill/home-build/pca9685.h --output pca9685.h
  script:
    - go build -o $CI_PROJECT_DIR/wscgo-wpi-opiz.so -buildmode=plugin
  artifacts:
    paths:
      - wscgo-wpi-opiz.so
  tags:
    - grill-tamasi
    - opiz
    - golang
  
package:main:
  stage: package
  dependencies:
    - build:main
  script:
    - envsubst < wscgo.cfg.tpl > wscgo.cfg
    - equivs-build wscgo.cfg
  artifacts:
    paths:
      - "*.deb"
  tags:
    - grill-tamasi
    - equivs    

package:opiz:
  stage: package
  dependencies:
    - build:opiz
  script:
    - curl -L https://github.com/balazsgrill/WiringOP-Zero/releases/download/v2.0-pwmfix/libwiringPi.so.2.0 --output libwiringPi.so.2.0
    - ln -s libwiringPi.so.2.0 libwiringPi.so
    - envsubst < wscgo-opiz.cfg.tpl > wscgo-opiz.cfg
    - equivs-build wscgo-opiz.cfg
  artifacts:
    paths:
      - "*.deb"
  tags:
    - grill-tamasi
    - equivs

package:rpizw:
  stage: package
  dependencies:
    - build:rpizw
  script:
    - envsubst < wscgo-rpizw.cfg.tpl > wscgo-rpizw.cfg
    - equivs-build wscgo-rpizw.cfg
  artifacts:
    paths:
      - "*.deb"
  tags:
    - grill-tamasi
    - equivs

integration-test:rpizw:
  stage: integration-test
  dependencies:
    - package:rpizw
  script:
    - dpkg --dry-run -i wscgo-rpizw_${VERSION}_armhf.deb
  tags:
    - grill-tamasi
    - rpizw

integration-test:opiz:
  stage: integration-test
  dependencies:
    - package:opiz
  script:
    - dpkg --dry-run -i wscgo-opiz_${VERSION}_armhf.deb
  tags:
    - grill-tamasi
    - opiz

deb:
  stage: deploy
  dependencies:
    - package:opiz
    - package:rpizw
    - package:main
  script:
    - curl -X PUT -T wscgo-opiz_${VERSION}_armhf.deb -u$BINTRAY_USER:$BINTRAY_APIKEY "https://api.bintray.com/content/balazsgrill/home/wscgo-opiz/${VERSION}/pool/main/w/wscgo-opiz/wscgo-opiz_${VERSION}_armhf.deb;deb_distribution=unstable;deb_component=main;deb_architecture=armhf;publish=1"
    - curl -X PUT -T wscgo-rpizw_${VERSION}_armhf.deb -u$BINTRAY_USER:$BINTRAY_APIKEY "https://api.bintray.com/content/balazsgrill/home/wscgo-rpizw/${VERSION}/pool/main/w/wscgo-rpizw/wscgo-rpizw_${VERSION}_armhf.deb;deb_distribution=unstable;deb_component=main;deb_architecture=armhf;publish=1"
    - curl -X PUT -T wscgo-opiz_${VERSION}_armhf.deb -u$BINTRAY_USER:$BINTRAY_APIKEY "https://api.bintray.com/content/balazsgrill/wscgo/wscgo-opiz/${VERSION}/pool/main/w/wscgo-opiz/wscgo-opiz_${VERSION}_armhf.deb;deb_distribution=unstable;deb_component=main;deb_architecture=armhf;publish=1"
    - curl -X PUT -T wscgo-rpizw_${VERSION}_armhf.deb -u$BINTRAY_USER:$BINTRAY_APIKEY "https://api.bintray.com/content/balazsgrill/wscgo/wscgo-rpizw/${VERSION}/pool/main/w/wscgo-rpizw/wscgo-rpizw_${VERSION}_armhf.deb;deb_distribution=unstable;deb_component=main;deb_architecture=armhf;publish=1"
    - curl -X PUT -T wscgo_${VERSION}_armhf.deb -u$BINTRAY_USER:$BINTRAY_APIKEY "https://api.bintray.com/content/balazsgrill/home/wscgo/${VERSION}/pool/main/w/wscgo/wscgo_${VERSION}_armhf.deb;deb_distribution=unstable;deb_component=main;deb_architecture=armhf;publish=1"
    - curl -X PUT -T wscgo_${VERSION}_armhf.deb -u$BINTRAY_USER:$BINTRAY_APIKEY "https://api.bintray.com/content/balazsgrill/home/wscgo/${VERSION}/pool/main/w/wscgo/wscgo_${VERSION}_armhf.deb;deb_distribution=unstable;deb_component=main;deb_architecture=armhf;publish=1"
  only:
    - master
  tags:
    - grill-tamasi
