name: Main
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Get current time
      uses: srfrnk/current-time@v1.1.0
      id: current-time
      with:
        format: YYYYMMDDHHss

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Install tools
      run: |
        sudo apt update
        sudo apt-get install -y gcc-arm-linux-gnueabihf build-essential devscripts debhelper gettext-base

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - id: dotenv
      uses: falti/dotenv-action@v0.2.3

    - name: Test
      run: |
        go test -v ./devices
        go test -v ./protocol
        go test -v ./config

    - name: Package
      env:
        VERSION: "${{ steps.dotenv.outputs.version }}-${{ steps.current-time.outputs.formattedTime }}"
        GOOS: "linux"
        GOARCH: "arm"
        GOARM: "5"
        CGO_ENABLED: "1"
        CC: "arm-linux-gnueabihf-gcc"
      run: |
        echo "Version: $VERSION"
        envsubst < debian/changelog.tpl > debian/changelog
        dpkg-buildpackage --target-arch armhf --host-arch armhf -b
        cp ../wscgo_${{ steps.dotenv.outputs.version }}-${{ steps.current-time.outputs.formattedTime }}_armhf.deb ./
    
    - uses: actions/upload-artifact@v1
      with:
        name: binary
        path: "wscgo"

    - uses: actions/upload-artifact@v1
      with:
        name: debian-package
        path: "wscgo_${{ steps.dotenv.outputs.version }}-${{ steps.current-time.outputs.formattedTime }}_armhf.deb"
    
    - name: Publish CI package
      if: github.ref == 'refs/heads/master'
      uses: bpicode/github-action-upload-bintray@v0.9.0
      with:
        file: "wscgo_${{ steps.dotenv.outputs.version }}-${{ steps.current-time.outputs.formattedTime }}_armhf.deb"
        api_user: balazsgrill
        api_key: "${{ secrets.BINTRAY_APIKEY }}" # An API key can be obtained from the user profile page.
        repository_user: balazsgrill
        repository: home
        package: wscgo
        version: '${{ steps.dotenv.outputs.version }}-${{ steps.current-time.outputs.formattedTime }}'
        upload_path: pool/main/w # Typical for debian repository layout
        publish: 1
        calculate_metadata: true # Schedule metadata calcuation after upload
        deb_distribution: unstable
        deb_component: main
        deb_architecture: armhf

    - name: Release package
      if: startsWith(github.ref, 'refs/tags/v')
      uses: bpicode/github-action-upload-bintray@v0.9.0
      with:
        file: "wscgo_${{ steps.dotenv.outputs.version }}-${{ steps.current-time.outputs.formattedTime }}_armhf.deb"
        api_user: balazsgrill
        api_key: "${{ secrets.BINTRAY_APIKEY }}" # An API key can be obtained from the user profile page.
        repository_user: balazsgrill
        repository: wscgo
        package: wscgo
        version: '${{ steps.dotenv.outputs.version }}-${{ steps.current-time.outputs.formattedTime }}'
        upload_path: pool/main/w # Typical for debian repository layout
        publish: 1
        calculate_metadata: true # Schedule metadata calcuation after upload
        deb_distribution: unstable
        deb_component: main
        deb_architecture: armhf
